import {
	TbAlertTriangle,
	TbChartHistogram,
	TbCircleCheck,
	TbDiamond,
	TbInfoCircle,
	TbInfoTriangle,
	TbLayoutDashboard,
	TbLayoutSidebar,
	TbLayoutSidebarFilled,
	TbLoader,
	TbLoader2,
	TbLogout,
	TbMessage,
	TbMoonStars,
	TbPaint,
	TbSchool,
	TbSettings2,
	TbSunHigh,
	TbUser
} from 'react-icons/tb'

export const Icons = {
	chat: TbMessage,
	circleCheckFilled: TbCircleCheck,
	circleInfoFilled: TbInfoCircle,
	dashboard: TbLayoutDashboard,
	learning: TbSchool,
	loader: TbLoader,
	loader2: TbLoader2,
	logo: TbDiamond,
	logout: TbLogout,
	moon: TbMoonStars,
	profile: TbUser,
	reports: TbChartHistogram,
	settings: TbSettings2,
	sidebarClose: TbLayoutSidebarFilled,
	sidebarOpen: TbLayoutSidebar,
	sun: TbSunHigh,
	theme: TbPaint,
	triangleAlertFilled: TbAlertTriangle,
	triangleInfoFilled: TbInfoTriangle
}
